### ISSUE TITLE
crashing when trying to stream

### ISSUE THREAD

**Issue by Stevenzocker** [verticalsync/Sunroof#12]
### Operating System

Endeavour OS

### Linux Only ~ Desktop Environment

Hyprland on Wayland

### What happens when the bug or crash occurs?

Almost every time I try to stream anything and selecting a video source the App just crashes

### What is the expected behaviour?

I expect Suncord to apply the selected video source and start the streaming process normally

### How do you recreate this bug or crash?

1. Open Suncord
2. Join a voice channel
3. Click on the start stream button

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Sunroof and Suncord versions
- [X] This issue occurs on an official release (not just the AUR packages)

**Comment by verticalsync** [comment]
Most of these issues are caused on Vesktop. You'll be better off switching to Vesktop, reproducing the bug, and then reporting it on their github.
